Complete Menubar implementation
NatalieTanML/foremcee pull request #20
Opened 2021-06-14 08:56 UTC by NatalieTanML

Closes #19.

The app's main functionalities (record, edit, delete) are implemented.

Updating of settings (hotkey) will be implemented in a separate branch in the near future, as well as any other QoL features.

2021-06-14 17:19 UTC, chuabingquan commented on src/App.tsx
> +// };
I think we can remove this commented block of code out since it's no longer needed.

2021-06-14 19:32 UTC, chuabingquan requested changes
Overall we are almost there, do look at the reviews and let me know if there are any issues. Great work! 😸

2021-06-14 19:32 UTC, chuabingquan commented on src/components/ListButton/index.tsx
> +const ListButton = ({ onClick, isLoading, children, cname = '' }: Props) => {
Would it be more ideal if we pick a more specific name for `cname` instead? At first glance I'm not really sure what it is supposed to represent.

2021-06-14 19:32 UTC, chuabingquan commented on src/components/ListButton/index.tsx
> +  ) : (
Would it be possible to merge the conditional rendering for `disabled`, `className`, and `CgSpinner` into one single `button`? One suggestion might be to store `className` and the contents of `IconContext.Provider` in local variables, then supply them wherever needed in the single button declaration.

E.g.

```tsx
const className = isLoading ? 'class names for loading state' : ' class names otherwise';
const btnContent = isLoading ? <CgSpinner /> : children;
const iconCtxStyle = {
  size: '1.25em',
  ...(isLoading && { className: 'animate-spin' }),
};

return (
  <button
    disabled={isLoading}
    className={className}
  >
    <IconContext.Provider value={iconCtxStyle}>
      {btnContent}
    </IconContext.Provider>
  </button>
);
```

This way, I think the code would be DRY and easier to read and understand.

2021-06-14 19:32 UTC, chuabingquan commented on src/components/ListItem/index.tsx
> +const ListItem = (prop: { rec: Recording; recM: RecordingManager }) => {
1. Might I suggest `recording` and `recordingManager` for the props names instead for better readability and clarity.
2. The type annotation for props can be declared as a separate type, this way you could destructure your prop argument without compromising on readability.

e.g.
 
```tsx
type Props = {
  recording: Recording;
  recordingManager: RecordingManager;
}

const ListItem = ({ recording, recordingManager } : Props) => {
  ...
};
```

#### Side Note
It appears that using `prop-types` is the accepted™ way at this point of time for prop type annotations. I guess we both need to get over the JS-fatigue and catch up with this at some point in the future.

2021-06-14 19:32 UTC, chuabingquan commented on src/components/ListItem/index.tsx
> +            recordingManager.deleteRecording(recording);
It might be good to `await` this promise and perform some kind of error handling.

2021-06-14 19:32 UTC, chuabingquan commented on src/recording-manager/RecordingManager.ts
> +      .reverse();
I'm not sure if there's any guarantees that `readdir` would return the file names in any kind of order at all. If not, you could explore using `sort` instead, e.g. `recordings.sort((x, y) => x.datetime - y.datetime)`.

__Note that sort would mutate the array in place, but I think it's acceptable here although the influence of haskell on me is making this feel like an offence__ 🤣

2021-06-14 19:32 UTC, chuabingquan commented on src/views/MenuBar.tsx
> +  }, [recordings]);
It should be sufficient to remove the `useEffect` call here and shift the block of logic into a helper function instead (e.g. `groupRecordingsByDate`) as there's no side-effect being performed here (e.g. network calls).

Instead, you could refer to the previous `useEffect` call and apply the helper function on the yielded recordings. This way, `setRecordings` can be replaced with `setGroupRecordings`, allowing us to eliminate `recordings` as a redundant state while keeping the `useEffect` call clear and concise.

e.g.

```tsx
const groupRecordingsByDate = (recordings: Recording[]) => {
  // Shift logic of the current useEffect that I'm reviewing here
  // and return an organised set of Recordings.
};

// Your previous useEffect call.
useEffect(() => {
  let cancel = false;
  recordingManager
    ?.getRecordings()
    .then((recs) => {
      if (!cancel) {
        setGroupRecordings(
          groupRecordingsByDate(recs)
        );
      }
    })
    .catch(console.error);
      
  // Return cleanup function here.
});
```

2021-06-15 06:08 UTC, NatalieTanML commented on src/components/ListButton/index.tsx
> +const ListButton = ({ onClick, isLoading, children, cname = '' }: Props) => {
i've renamed it to 'addStyleName'

2021-06-15 17:09 UTC, chuabingquan approved these changes
LGTM.

2021-06-15 17:09 UTC, merged